# fly.toml app configuration file generated for achieve-insurances-api on 2025-02-18T13:07:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'achieve-insurances-api'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
